version: '3'
services:
  project1:
    build:
      context: ./project1
      dockerfile: Dockerfile
    container_name: project1-container
    restart: always
    working_dir: /var/www/project1
    volumes:
      - ./project1:/var/www/project1

  project2:
    build:
      context: ./project2
      dockerfile: Dockerfile
    container_name: project2-container
    restart: always
    working_dir: /var/www/project2
    volumes:
      - ./project2:/var/www/project2

  nginx:
    image: nginx:1.19-alpine
    container_name: nginx-container
    restart: always
    ports:
      - 8081:80
      - 8082:81
    volumes:
      - ./nginx-config:/etc/nginx/conf.d
      - ./project1:/var/www/project1
      - ./project2:/var/www/project2
